In [2]:
import pandas as pd

In [4]:
Aug_with_Noise = pd.read_csv("Added_Noise_augmented_data.csv")
Aug_with_CTGAN = pd.read_csv("augmented_merge_CTGAN.csv")

In [5]:
df_augumented_With_Noise_and_CTGAN = pd.concat([Aug_with_Noise, Aug_with_CTGAN], ignore_index=True)
df_augumented_With_Noise_and_CTGAN = df_augumented_With_Noise_and_CTGAN.drop_duplicates()

In [6]:
df_augumented_With_Noise_and_CTGAN.describe()

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,...,Occupation_Manual Labor,Occupation_Nurse,Occupation_Office Worker,Occupation_Retired,Occupation_Sales Representative,Occupation_Salesperson,Occupation_Scientist,Occupation_Software Engineer,Occupation_Student,Occupation_Teacher
count,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,...,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000,2981.000000
mean,0.456223,38.945991,7.251448,6.235997,27.463603,5.575442,1.879571,1.568242,77.785545,9327.986246,...,0.055709,0.047927,0.087178,0.053951,0.056552,0.054010,0.073610,0.049527,0.091297,0.054159
std,0.498163,12.813771,1.826653,1.311359,36.276952,2.420983,0.950409,0.192761,12.215406,3693.584262,...,0.231093,0.219079,0.282529,0.224552,0.230146,0.225469,0.265808,0.215557,0.290066,0.227064
min,0.000000,5.000000,2.000000,0.782057,0.000000,0.000000,-1.000000,1.031915,44.000000,2000.000000,...,-0.023286,-0.026594,-0.023086,-0.016245,-0.021752,-0.017705,-0.013974,-0.020838,-0.025315,-0.022143
25%,0.000000,30.000000,6.000000,5.741391,3.000000,4.000000,1.000000,1.447059,69.630610,7000.000000,...,-0.001348,-0.002851,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,38.000000,7.000000,6.307403,4.000000,6.000000,2.000000,1.562500,77.000000,9000.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,47.000000,8.253346,7.000000,49.000000,7.681207,3.000000,1.696750,86.577249,11000.000000,...,0.000000,0.000000,0.000000,0.004194,0.000108,0.002086,0.002930,0.001113,0.000000,0.000000
max,1.000000,90.000000,12.000000,10.000000,149.000000,13.000000,3.000000,2.250000,105.000000,23037.000000,...,1.107197,1.069484,1.218362,1.250328,1.268912,1.301662,1.322404,1.315223,1.119426,1.193558

In [7]:
df_augumented_With_Noise_and_CTGAN.to_csv("augmented_merge_Noise_and_CTGAN.csv", index=False)